### ISSUE TITLE
Value Error: Invalid Literal for int() with base 10:"causal"

### ISSUE THREAD

**Issue by omaruno** [IdoAmos/not-from-scratch#3]
python train.py experiment=lra/transformer-lra-cifar-mlm dataset.causal_lm=true dataset.mlm_prob=0.0 \
model.layer.causal=true train.manual_checkpoints=true

With the second experiments Iam getting the following error:
    last_key = int(last)
               ^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'causal'

Should I change some parameter in the code?

**Comment by IdoAmos** [comment]
There was a small typo in the readme file that I fixed - the command should have been:
`python train.py experiment=lra/transformer-lra-cifar-mlm dataset.causal_lm=true dataset.mlm_prob=0.0 model.layer.0.causal=true train.manual_checkpoints=true`

can you clarify what you mean by the second experiments?
